'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class FERRETERIAEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FERRETERIAEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property categoria() As DbSet(Of categoria)
    Public Overridable Property cliente() As DbSet(Of cliente)
    Public Overridable Property detalle() As DbSet(Of detalle)
    Public Overridable Property producto() As DbSet(Of producto)
    Public Overridable Property tipo_usuario() As DbSet(Of tipo_usuario)
    Public Overridable Property usuario() As DbSet(Of usuario)
    Public Overridable Property venta() As DbSet(Of venta)

    Public Overridable Function ControProd(estado As Nullable(Of Integer), stockminimo As Nullable(Of Integer)) As ObjectResult(Of ControProd_Result)
        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("estado", estado), New ObjectParameter("estado", GetType(Integer)))

        Dim stockminimoParameter As ObjectParameter = If(stockminimo.HasValue, New ObjectParameter("stockminimo", stockminimo), New ObjectParameter("stockminimo", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ControProd_Result)("ControProd", estadoParameter, stockminimoParameter)
    End Function

    Public Overridable Function reporte_prod(estado As Nullable(Of Integer), minstock As Nullable(Of Integer)) As ObjectResult(Of reporte_prod_Result)
        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("estado", estado), New ObjectParameter("estado", GetType(Integer)))

        Dim minstockParameter As ObjectParameter = If(minstock.HasValue, New ObjectParameter("minstock", minstock), New ObjectParameter("minstock", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reporte_prod_Result)("reporte_prod", estadoParameter, minstockParameter)
    End Function

    Public Overridable Function reporte_producto() As ObjectResult(Of reporte_producto_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reporte_producto_Result)("reporte_producto")
    End Function

    Public Overridable Function reporte_usuario() As ObjectResult(Of reporte_usuario_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reporte_usuario_Result)("reporte_usuario")
    End Function

    Public Overridable Function reporte_ventas(fecha As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of reporte_ventas_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reporte_ventas_Result)("reporte_ventas", fechaParameter, fecha2Parameter)
    End Function

    Public Overridable Function reportefechas(fecha As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of reportefechas_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reportefechas_Result)("reportefechas", fechaParameter, fecha2Parameter)
    End Function

    Public Overridable Function sp_comprobante() As ObjectResult(Of sp_comprobante_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_comprobante_Result)("sp_comprobante")
    End Function

    Public Overridable Function sp_compUna(idVenta As Nullable(Of Integer)) As ObjectResult(Of sp_compUna_Result)
        Dim idVentaParameter As ObjectParameter = If(idVenta.HasValue, New ObjectParameter("idVenta", idVenta), New ObjectParameter("idVenta", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_compUna_Result)("sp_compUna", idVentaParameter)
    End Function

    Public Overridable Function sp_unaVenta111() As ObjectResult(Of sp_unaVenta111_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_unaVenta111_Result)("sp_unaVenta111")
    End Function

    Public Overridable Function sp_unEmpleadoVentas(idEmpleado As Nullable(Of Integer), fechaDesde As Nullable(Of Date), fechaHasta As Nullable(Of Date)) As ObjectResult(Of sp_unEmpleadoVentas_Result)
        Dim idEmpleadoParameter As ObjectParameter = If(idEmpleado.HasValue, New ObjectParameter("idEmpleado", idEmpleado), New ObjectParameter("idEmpleado", GetType(Integer)))

        Dim fechaDesdeParameter As ObjectParameter = If(fechaDesde.HasValue, New ObjectParameter("fechaDesde", fechaDesde), New ObjectParameter("fechaDesde", GetType(Date)))

        Dim fechaHastaParameter As ObjectParameter = If(fechaHasta.HasValue, New ObjectParameter("fechaHasta", fechaHasta), New ObjectParameter("fechaHasta", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_unEmpleadoVentas_Result)("sp_unEmpleadoVentas", idEmpleadoParameter, fechaDesdeParameter, fechaHastaParameter)
    End Function

    Public Overridable Function sp_Venta() As ObjectResult(Of sp_Venta_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_Venta_Result)("sp_Venta")
    End Function

    Public Overridable Function sp_ventaPorfecha(fecha As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of sp_ventaPorfecha_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_ventaPorfecha_Result)("sp_ventaPorfecha", fechaParameter, fecha2Parameter)
    End Function

    Public Overridable Function sp_ventaPorfecha1(fecha As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of sp_ventaPorfecha1_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_ventaPorfecha1_Result)("sp_ventaPorfecha1", fechaParameter, fecha2Parameter)
    End Function

    Public Overridable Function Vdeldia(fecha As Nullable(Of Date)) As ObjectResult(Of Vdeldia_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Vdeldia_Result)("Vdeldia", fechaParameter)
    End Function

    Public Overridable Function VentasDelDia(fecha As Nullable(Of Date)) As ObjectResult(Of VentasDelDia_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasDelDia_Result)("VentasDelDia", fechaParameter)
    End Function

End Class
