'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cliente
    Public Property id_cliente As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property domicilio As String
    Public Property email As String
    Public Property dni_cliente As Nullable(Of Integer)
    Public Property fecha_nac As Nullable(Of Date)
    Public Property telefono As Nullable(Of Integer)
    Public Property estado As Boolean

    Public Overridable Property venta As ICollection(Of venta) = New HashSet(Of venta)

End Class
