'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalle
    Public Property id_detalle As Integer
    Public Property id_venta As Nullable(Of Integer)
    Public Property id_producto As Nullable(Of Integer)
    Public Property cantidad As Nullable(Of Integer)
    Public Property precio_unitario As Nullable(Of Integer)

    Public Overridable Property producto As producto
    Public Overridable Property venta As venta

End Class
