'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class producto
    Public Property id_producto As Integer
    Public Property id_categoria As Nullable(Of Integer)
    Public Property nombre As String
    Public Property descripcion As String
    Public Property stock As Nullable(Of Integer)
    Public Property stock_minimo As Nullable(Of Integer)
    Public Property precio_compra As Nullable(Of Single)
    Public Property precio_venta As Nullable(Of Single)
    Public Property estado As Boolean
    Public Property codigo_pro As Nullable(Of Integer)

    Public Overridable Property categoria As categoria
    Public Overridable Property detalle As ICollection(Of detalle) = New HashSet(Of detalle)

End Class
