'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class venta
    Public Property id_venta As Integer
    Public Property id_cliente As Nullable(Of Integer)
    Public Property fecha_ven As Nullable(Of Date)
    Public Property id_usuario As Nullable(Of Integer)
    Public Property precio_total As Nullable(Of Single)

    Public Overridable Property cliente As cliente
    Public Overridable Property detalle As ICollection(Of detalle) = New HashSet(Of detalle)
    Public Overridable Property usuario As usuario

End Class
